### ISSUE TITLE
Small improvements

### ISSUE THREAD

**Issue by ggabrovski** [renancaraujo/photo_view#1]
First I want to thank you for this widget, it will be very useful if you can add:
- Remove the fixed black color background form _PhotoViewImageWrapperState line 185 or make it custom.
- Now is possible to zoom out too far, it should let you—but then shrink back to the initial zoom size.
- The same is true for zoom in, maybe it will be good if we can set the max value for scale.

**Comment by renancaraujo** [comment]
Those are really good suggestions, thanks.
I'm hoping to get into some extra options on the next days.

**Comment by renancaraujo** [comment]
Thanks to #3 and recent commits, i think all of those suggestions are covered by now. 
Thank you for pointing it out.

**Comment by dpedrinha** [comment]
I still see the back background. I'm using the PUB version.

**Comment by dpedrinha** [comment]
Hmm I just noticed you added a backgroundDecoration prop.
Would be nice to have it transparent by default though. Me and probably other people out there need transparent PNGs and this black background took me some time to figure out.
Great plugin by the way.

**Comment by renancaraujo** [comment]
Probably there are already tons of people using PhotoView by now. I will avoid major layout chages like this default swap. It is pretty simple to customize it. 
We can simplify docs this regard.

**Comment by dpedrinha** [comment]
Makes sense. It's good that you think this way.
Maybe keep it for a major update. A simple update warning should do the trick.
