### ISSUE TITLE
minScale / maxScale don't work

### ISSUE THREAD

**Issue by gilgold** [renancaraujo/photo_view#104]
I am running the example Gallery from this repo, but when zooming in / out past the limit in minScale / maxScale the image does not snap back - it just stays there very small / large (depending if you are zooming in or out)

**Comment by tavrinnn** [comment]
Can confirm that the above-mentioned bug exists

**Comment by renancaraujo** [comment]
That is an expected behavior, when `PhotoViewScaleState` is set to `zooming`, the panning gesture of the PageView is locked. We should figure out a way to make it not lock weh image is smaler than `PhotoViewComputedScale.contained`

PRs are welcome.

**Comment by tavrinnn** [comment]
Correct me if i'm wrong but isn't @gilgold original issue with the fact that the min / max scale limits aren't obeyed? I noticed this as well when I was testing... It works fine in the "Limited Scale" demo... but when you attempt to set the min / max scale limits in the PhotoViewGallery it doesn't get respected and you can zoom in or zoom out to crazy proportions.

**Comment by gilgold** [comment]
@tavrinnn correct, that is what I meant.

**Comment by renancaraujo** [comment]
Sorry, my bad. Dynamic reading didn't work this time.

**Comment by gilgold** [comment]
I created a pull request to fix this - seems to work on my local
https://github.com/renancaraujo/photo_view/pull/107

**Comment by renancaraujo** [comment]
Thanks for your contribution
