### ISSUE TITLE
PhotoViewGallery swipe glitch

### ISSUE THREAD

**Issue by tavrinnn** [renancaraujo/photo_view#105]
I stumbled across an interesting glitch. If you zoom in / out of an image and then attempt to swipe across to the next image; the gallery will occasionally glitch and ignore the swipe gesture. At this point it appears to be permanently glitched and scrolling left / right to navigate through the gallery does not work.

**Comment by renancaraujo** [comment]
Dupe of #104

**Comment by renancaraujo** [comment]
That is expected behavior, when `PhotoViewScaleState` is set to `zooming`, the panning gesture of the PageView is locked. We should figure out a way to make it not lock when image is smaller than `PhotoViewComputedScale.contained`

PRs are welcome.
