### ISSUE TITLE
Call the listener when the widget offset/scale are initialized?

### ISSUE THREAD

**Issue by Khalamar** [renancaraujo/photo_view#106]
Maybe I'm missing something and this is not how it's supposed to work.

I embed the photo_view controller in a parent to display rulers. In order to update the rulers, I set up a listener and I adapt the marks and ticks and whatnot of my rulers according to the offset/scale values coming through the listener.

This works great, except for the very first frame, when the photo_view widget is rendered for the first time. The listener is only called when the photo_view widget is panned/zoomed, so I cannot update my rulers.

Since the photo_view offset defaults to origin, and the scale can be set through initialScale, I hacked a way to use those default values when building my layout. However, it would be nice to have the listener be called so I can use the initial scale I wanted to use in the first place (PhotoViewComputedScale.covered)

**Comment by renancaraujo** [comment]
@Khalamar First of all, I strongly advise you to use the `outputStateStream` to listen for changes in the state, we should specify this on the docs. 

PhotoViewController has a`initial` field, in order to solve this, we should skin this initial state on PhotoView's mount.

**Comment by Khalamar** [comment]
Ah, yes, I simply called .addListener to the PhotoViewController, I have now added a proper listener through PhotoViewController.outputStateStream.listen(listener), which gives me more information about what's going on (I suppose the event member will be useful). Thanks!

**Comment by miehilmie** [comment]
@Khalamar I notice it is not really reliable to rely on `outputStateStream` to listen for change because some of the listeners accessing `ValueNotifier` value which might resulting in race-condition. For example, in `photo_view.scaleStateListener`, we subscribe to stream value but did access controller value which the state is not consistent.

```
I/flutter (19678): _PhotoViewImageWrapperState.onScaleUpdate newScaleState PhotoViewScaleState.zooming
I/flutter (19678): PhotoViewController._changeListener value.scaleState PhotoViewScaleState.zooming
I/flutter (19678): PhotoViewController.updateMultiple prevValue.scaleState PhotoViewScaleState.initial
I/flutter (19678): PhotoViewController.updateMultiple value.scaleState PhotoViewScaleState.zooming
I/flutter (19678): _PhotoViewImageWrapperState.onScaleUpdate newScaleState PhotoViewScaleState.zooming
I/flutter (19678): PhotoViewController._changeListener value.scaleState PhotoViewScaleState.zooming
I/flutter (19678): PhotoViewController.updateMultiple prevValue.scaleState PhotoViewScaleState.zooming
I/flutter (19678): PhotoViewController.updateMultiple value.scaleState PhotoViewScaleState.zooming
I/flutter (19678): _PhotoViewState.scaleStateListener value.scaleState PhotoViewScaleState.zooming
I/flutter (19678): _PhotoViewState.scaleStateListener controller.scaleState PhotoViewScaleState.zooming
I/flutter (19678): _PhotoViewState.scaleStateListener controller.prevValue.scaleState PhotoViewScaleState.zooming
```

As you can see, `scaleStateListener` listens to `outputStateStream` while accessing `PhotoViewController` value causing issue skipping callback `scaleStateChangedCallback`.

**Comment by renancaraujo** [comment]
@miehilmie I think we have a solution for this: #120
