### ISSUE TITLE
How to modify can set the double-click position to zoom in, and slide between the two fingers to zoom in

### ISSUE THREAD

**Issue by LebenNNA** [renancaraujo/photo_view#109]
How to modify can set the double-click position to zoom in, and slide between the two fingers to zoom in

**Comment by renancaraujo** [comment]
Could you explain better what behavior do you want?
Have in mind that PhotoView does not support custom gesture mapping, but ideas are always welcome.

**Comment by LebenNNA** [comment]
Maybe I didn't describe it clearly. The general function is to zoom in and out around a certain point, instead of zooming in and out at the center. @renancaraujo

**Comment by renancaraujo** [comment]
PhotoView has a `basePosition` which determines the position of the content (image) in relation to the container.
 I think it may would solve your problem. If this is not the case, you could try to change it in two places: 

- _PhotoViewImageWrapperState.onScaleUpdate
Receives a `details` with a field called `focalPoint`, you can try to override that.

- _PhotoViewImageWrapperState.build
Both `Transform` wodgets has an `alignment` field provided, you acn tru to verride that as well.

That is a very specific situation in which is not applicable to be included as a feature (or at least it is not a priority).

**Comment by renancaraujo** [comment]
@LebenNNA Let me know if you were able to achieve this outcome. Closing for now.

**Comment by JunhaoHuang0615** [comment]
How to achieve this feature now?
