### ISSUE TITLE
i don't need zoom out image after its original size

### ISSUE THREAD

**Issue by Adilkp796** [renancaraujo/photo_view#110]
I don't need zoom out image after its original size.

**Comment by Adilkp796** [comment]
I fix that problem  
I get image's original size by calling this method `getScaleForScaleState(widget.controller.scaleState, widget.scaleBoundaries)` 
and check with if condition by `if(getInitialScale <= newScale)` on onScaleUpdate() method
` double newScale = _scaleBefore * details.scale;`

**Comment by hugocbpassos** [comment]
A very simple way to do that is setting `minScale` to `PhotoViewComputedScale.contained`.
