### ISSUE TITLE
Wrapping the gallery inside a grid

### ISSUE THREAD

**Issue by fvisticot** [renancaraujo/photo_view#111]
It would be fine to provide GridView integration to display gallery fist time

**Comment by renancaraujo** [comment]
The example app has an awesome sample of a case integrating the gallery with a holistic view of images in the gallery. Therefore, this integration would be awesome as an external screen. 

![In action](https://user-images.githubusercontent.com/6718144/46573612-2e967d00-c96e-11e8-9b9f-a70d5a62861d.gif)


What can be done is an screen in teh exmple app where a GridView in a screen [similar to this one](https://github.com/renancaraujo/photo_view/blob/master/example/lib/screens/examples/gallery_example.dart#L37). 


PRs are welcome 😁.

**Comment by renancaraujo** [comment]
I will close this issue for now. If you think that your doubt/request has not been understood, feel free to reopen it. Thanks.
