### ISSUE TITLE
 [Question] Dynamic PhotoViewGallery

### ISSUE THREAD

**Issue by dmazlum** [renancaraujo/photo_view#113]
Hello,

I need to create dynamic PhotoViewGalleryPageOptions. How to create dynamic fullscreen gallery from json.

My loop

`var subData = subcats.gallery;

if (subcats != null) {
  var lengthOfList = subData.length;

  for (int i = 0; i < lengthOfList; i++) {
    Galleries subcat = subData[i];

    // Image URL
    var imageURL = "http://10.0.2.2:8081/gallery/" + subcat.photoName;

    var listItem = new Container(
        constraints: BoxConstraints.expand(
          height: MediaQuery.of(context).size.height,
        ),
        decoration: BoxDecoration(
          border: new Border.all(color: Colors.blueGrey[200]),
          boxShadow: [
            BoxShadow(
              color: Colors.black12,
              blurRadius: 10.0,
            )
          ],
        ),
        padding: const EdgeInsets.symmetric(horizontal: 5.0),
        child: GestureDetector(
          onTap: () {
            Navigator.push(
              context,
              MaterialPageRoute(
                builder: (context) => FullScreenWrapper(
                      imageProvider: NetworkImage(imageURL),
                      index: i,
                    ),
              ),
            );
          },
          child: new CachedNetworkImage(
            imageUrl: imageURL,
            fit: BoxFit.cover,
            placeholder: (context, url) => new CircularProgressIndicator(),
            errorWidget: (context, url, error) => new Icon(
                  Icons.error,
                  color: Colors.red,
                ),
          ),
        ));

    listElementWidgetList.add(listItem);
  }
}`

My Wrapper

```
class FullScreenWrapper extends StatefulWidget {
FullScreenWrapper({
this.imageProvider,
this.loadingChild,
this.backgroundDecoration,
this.minScale,
this.maxScale,
this.initialScale,
this.basePosition = Alignment.center,
this.index,
}) : pageController = PageController(initialPage: index);

final ImageProvider imageProvider;
final Widget loadingChild;
final Decoration backgroundDecoration;
final dynamic minScale;
final dynamic maxScale;
final dynamic initialScale;
final Alignment basePosition;
final int index;
final PageController pageController;

@override
State createState() {
return _FullScreenWrapperState();
}
}

class _FullScreenWrapperState extends State {
int currentIndex;

@override
void initState() {
currentIndex = widget.index;
super.initState();
}

void onPageChanged(int index) {
setState(() {
currentIndex = index;
});
}

@override
Widget build(BuildContext context) {
return Scaffold(
body: Container(
constraints: BoxConstraints.expand(
height: MediaQuery.of(context).size.height,
),
child: Stack(
alignment: Alignment.bottomRight,
children: [
PhotoViewGallery(
pageOptions: [
PhotoViewGalleryPageOptions(
imageProvider: widget.imageProvider,
initialScale: PhotoViewComputedScale.contained * 0.9,
)
],
loadingChild: widget.loadingChild,
backgroundDecoration: widget.backgroundDecoration,
pageController: widget.pageController,
onPageChanged: onPageChanged,
),
],
),
),
);
}
}
```

**Comment by renancaraujo** [comment]
@dmazlum Check the example [code here](https://github.com/renancaraujo/photo_view/blob/0.2.4/example/lib/screens/examples/gallery/gallery_example.dart). Basically, you have to access the entire collection in the wrapper. There is, also, the new `.builder` the constructor in which renders the items in the gallery dynamically. [ Check the docs. ](https://pub.dartlang.org/documentation/photo_view/latest/photo_view_gallery/PhotoViewGallery-class.html)

I'm closing this issue for now. If you consider your question not solved, feel free to reopen it and let's move forward with the discussion.
