### ISSUE TITLE
PhotoViewGallery minScale

### ISSUE THREAD

**Issue by AhsanKhan231** [renancaraujo/photo_view#115]
How I can restrict image to zoomout from its initial scale ?

My Code:
<PhotoViewGalleryPageOptions>[
        PhotoViewGalleryPageOptions(
          initialScale: PhotoViewComputedScale.contained,
          minScale: PhotoViewComputedScale.covered,
          imageProvider: NetworkImage(imagePath),
          heroTag: "tag1",
        )]

I have tried from both properties i.e. covered and contained but I am able to zoom out the image as much as I can zoom out.

**Comment by renancaraujo** [comment]
> "How I can restrict image to zoom out from its initial scale?"


You should pass the same value in both `initialScale` and `minScale`.

```
[PhotoViewGalleryPageOptions(
  initialScale: PhotoViewComputedScale.contained,
  minScale: PhotoViewComputedScale.contained,
  imageProvider: NetworkImage(imagePath),
  heroTag: "tag1",
)]
```
Which version of PhotoView you are using btw?

**Comment by AhsanKhan231** [comment]
Still the same issue. I am using ^0.2.1 version. My overall code is mentioned below. Also Please advise me how I can show the image in full container height . Right now there are some extra background spacing showing from top and bottom.

return Stack(children: <Widget>[
      Padding(
        padding: const EdgeInsets.all(0.0),
        child: Container(
          height: screenSize.height / 1.9,
          child: PhotoViewGallery(
              pageOptions: <PhotoViewGalleryPageOptions>[
        PhotoViewGalleryPageOptions(
          initialScale: PhotoViewComputedScale.contained,
          minScale: PhotoViewComputedScale.contained,
          imageProvider: NetworkImage(imagePath),
          heroTag: "tag1",
        ),
      ],
              backgroundDecoration: BoxDecoration(color: Colors.white),
            )))]);

**Comment by AhsanKhan231** [comment]
@renancaraujo any solution?

**Comment by renancaraujo** [comment]
That depends on the relation between the ratio (width/height) of both container and image. If the ratio is smaller than the container, you should change the values in `initialScale` and `minScale`to `PhotoViewComputedScale.covered`

**Comment by renancaraujo** [comment]
@AhsanKhan231 Any update on this? I will close this issue for now. If you consider your question not solved, feel free to reopen it and let's move forward with the discussion.

**Comment by dpedrinha** [comment]
> That depends on the relation between the ratio (width/height) of both container and image. If the ratio is smaller than the container, you should change the values in `initialScale` and `minScale`to `PhotoViewComputedScale.covered`

I didn't get this part. Can you please explain the difference between covered and contained, please?

**Comment by renancaraujo** [comment]
@dpedrinha It is how the image is scaled in relation to the container.
Contained: As large as possible while still containing the source entirely within the target box.
Cvoered: As small as possible while still covering the entire target box.

**Comment by renancaraujo** [comment]
It is soimilar to how [BoxFit](https://api.flutter.dev/flutter/painting/BoxFit-class.html) fits image.

**Comment by dpedrinha** [comment]
I see.
So contained may have empty spaces to show the entire image while covered may have some clipping to fill the entire parent. Right?
Thanks for clearing it up.
