### ISSUE TITLE
[BUG]in afterFirstLayout context.size is zero in release mode

### ISSUE THREAD

**Issue by hpsoar** [renancaraujo/photo_view#117]
**Describe the bug**
When run release mode, the initial size of the image is zero.

`customSize` not specified, thus null

so `_outerSize` is used for `_computedOuterSize`,

which is assigned in `afterFirstLayout`, and it's (0, 0) for release apk (Android device);

**Comment by renancaraujo** [comment]
Wow, so you are saying that [after_layout](https://pub.dartlang.org/packages/after_layout) does not work in release mode? 
I have tested it on one of my apps and it seems to work fine. 
It would help if you could share some more information about your case, like code.

**Comment by renancaraujo** [comment]
Due to some inactivity, I will close this issue for now. If you consider your question not solved, feel free to reopen it and let's move forward with the discussion.
