### ISSUE TITLE
[QUESTION] Zoom Listener

### ISSUE THREAD

**Issue by lorisgir** [renancaraujo/photo_view#118]
Hi, I'm quite new to flutter and dart so this might be a stupid question.
Is there a way to know if a user is zooming or not an image?
Cause I need to hide some widgets if the user start zooming an image and then show them back if the user release the zoom.

**Comment by seu1902** [comment]
You can try scaleStateChangedCallback, when zooming started, the state would turn to "PhotoViewScaleState.zooming", and when zooming released, it would come back to "PhotoViewScaleState.initial".

**Comment by renancaraujo** [comment]
@lorisgir Yes, there is.

Every time the user changes the scale, there is an input into the stream controller stream.
So the challenges you will have to tackle to achieve this:

- Use controllers on photoview, more precisely: PhotoViewController (Check docs [here](https://pub.dev/documentation/photo_view/0.3.3/photo_view/PhotoViewController-class.html), learn how to use them [here](https://pub.dev/documentation/photo_view/0.3.3/photo_view/PhotoView-class.html#controllers)). Every controller instance has a `outputStateStream`. So lets go to our next step:
- Learn how streams on flutter works
- Use RX. The behavior that you described can be solved with debounce. Like, once an `n` amount of time has passed sicne last entrance on the stream, you can fade elements back in.

I'm closing this issue for now. If you consider your question not solved, feel free to reopen it and let's move forward with the discussion.
