### ISSUE TITLE
Image flickers when using MemoryProvider

### ISSUE THREAD

**Issue by SocratesDz** [renancaraujo/photo_view#12]
Given the following scenario:
1. Given a url that links to an image, called e.g.: `imageUrl`.
2. Use a `Future` that returns the `bodyBytes` of the `http.Response` of `imageUrl` within `FutureBuilder`.
3. Inside the builder method of `FutureBuilder`, use such `bodyBytes` to create a `MemoryProvider` and with that, create a `PhotoView`.

When using `MemoryProvider`, the image selected "flickers" if the widget tree is re-rendered.

Here's a snippet to illustrate the scenario:
```
FutureBuilder(
      future: _loadImage(),
      builder: (context, snapshot) {
        if (snapshot.hasData) {
          var imageBytes = snapshot.data;
          return PhotoView(
              loadingChild: Center(child: CircularProgressIndicator()),
              imageProvider: MemoryImage(imageBytes)
          );
        }
        return CircularProgressIndicator();
      }
    );
```
Using a simple `Image` widget, one can avoid this behavior if the parameter `gaplessPlayback` is set to `true`. E.g.: `Image.memory(bytes, gaplessPlayback: true)`

Would you consider adding a factory constructor method that accepts an `Image`?

**Comment by renancaraujo** [comment]
The provider specified to photo view will be passed to an Image widget [(see the code)](https://github.com/renancaraujo/photo_view/blob/master/lib/photo_view_image_wrapper.dart#L219).

If you have an image URL, you could use photo view as follows: 
```dart
new PhotoView(
  imageProvider: new NetworkImage(imageAddress),
);
```
I think that will avoid this weird behavior.

**Comment by SocratesDz** [comment]
In my use case, I need to use a MemoryProvider, because I'm using a share intent to send the image, and it needs to be in bytes in order to encode them to base64, so I can send it. If I use NetworkImage, I think I'll have to download the image again to retrieve the bytes in order to use the share intent. So I'd have to download the same image twice.

See how they use `gaplessPlayback` in the `Image` widget [here](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/image.dart#L605). Maybe this can help.

**Comment by renancaraujo** [comment]
Just added your solution to 0.0.5
