### ISSUE TITLE
onTapUp onTapDown overriding higher onTap handler

### ISSUE THREAD

**Issue by jibbers42** [renancaraujo/photo_view#134]
**Is your feature request related to a problem? Please describe.**
I have a GestureDetector.onTap a bit higher in the tree then my PhotoView. I recently updated to the latest version and find that the new handlers override mine.

**Describe the solution you'd like**
If I pass null for onTapDown and onTapUp, I'd like my higher level GestureDetector.onTap to keep working. Inside PhotoView, a handler is setup even if i pass null, but it simply does a `return;`. I may be wrong, but I think if instead it set null to these handlers then my handler would still work.

https://github.com/renancaraujo/photo_view/blob/304652361fd64338abb9d0e28a53310569a1f167/lib/src/photo_view_image_wrapper.dart#L256-L267

**Comment by keitoro** [comment]
i am facing the same problem, it overrides my gesturedetector.

**Comment by renancaraujo** [comment]
Fixed on #139

**Comment by jibbers42** [comment]
This appears to be happening again from 5e4505659ed18fdaf26a0fbd21c2a1700d3a4b81
