### ISSUE TITLE
Small pictures are displayed in their original size instead of enlarged size

### ISSUE THREAD

**Issue by jlcool** [renancaraujo/photo_view#141]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**What is the current behavior?**

**Expected behavior**

**Screenshots**

**Is this a *feature* or report a *bug*?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. The output of flutter doctor can help too. **

**What is the expected behavior?**

**Which versions of Flutter/Photo View, and which browser / OS are affected by this issue? Did this work in previous versions of Photo View?**

**Additional context**

**Comment by renancaraujo** [comment]
Could you edit your issue explaining better which is the problem? The template fields are there to help. I'm closing this issue due to lack of information.

**Comment by jlcool** [comment]
Sorry, my English is too good. It's automatic translation. When I use hero to open a small picture, it will be enlarged to fill the screen, but I hope he is the original size display, how should this work?
