### ISSUE TITLE
The argument type 'Null Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'

### ISSUE THREAD

**Issue by pr0thean** [renancaraujo/photo_view#144]
**Describe the bug**
After upgading flutter I can not compile my project.

> Compiler message:
> file:///C:/Program%20Files/flutter/.pub-cache/hosted/pub.dartlang.org/photo_view-0.3.3/lib/photo_view.dart:380:24: Error: The argument type 'Null Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
>  - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Program%20Files/flutter/packages/flutter/lib/src/painting/image_stream.dart').
>  - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Program%20Files/flutter/packages/flutter/lib/src/painting/image_stream.dart').
> Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
>     stream.addListener(listener);
>                        ^
> file:///C:/Program%20Files/flutter/.pub-cache/hosted/pub.dartlang.org/photo_view-0.3.3/lib/photo_view.dart:382:29: Error: The argument type 'Null Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
>  - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Program%20Files/flutter/packages/flutter/lib/src/painting/image_stream.dart').
>  - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Program%20Files/flutter/packages/flutter/lib/src/painting/image_stream.dart').
> Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
>       stream.removeListener(listener);

I tried to follow the message and casted listener as ImageStreamListener and it compiled successfully but when I want to view the image I get this error:

> Another exception was thrown: type '(ImageInfo, bool) => Null' is not a subtype of type 'ImageStreamListener' in type cast

**Comment by ened** [comment]
Looks like this breaks on Flutters `master` channel.

**Comment by renancaraujo** [comment]
Sorry for teh delay. Looking into it now

**Comment by renancaraujo** [comment]
Released as 0.4.0
