### ISSUE TITLE
How to show image from api

### ISSUE THREAD

**Issue by jagdishjadeja** [renancaraujo/photo_view#148]
I have api which is returning me base64 image string
how do i show that image in PhotoView here ?

**Comment by renancaraujo** [comment]
You can use `dart:convert` to convert base64 to bytes[. Here is how.](https://stackoverflow.com/questions/15957427/how-do-i-encode-a-dart-string-in-base64)
Then you can use [MemoryImage](https://api.flutter.dev/flutter/painting/MemoryImage-class.html) ans pass as `imageProvider` to photo view.
