### ISSUE TITLE
[BUG] can't find photo_view in pub.dev

### ISSUE THREAD

**Issue by moonvader** [renancaraujo/photo_view#151]
Why photo_view can't be found in pub.dev packages?

**Comment by hugocbpassos** [comment]
It's visible for me:
https://pub.dev/packages/photo_view

However, I did notice that version `0.4.0` brought some problems, like the **[UNIDENTIFIED]** label and 0 **Health** score.

**Comment by renancaraujo** [comment]
Health zero due to lack of support to latest Flutter beta version (since we only support master on our latest eelease). Once Flutter 1.6 becomes beta, the score will be revised.
