### ISSUE TITLE
[BUG]The current Flutter SDK version is 1.5.4-hotfix.2.  Because skin_care_3 depends on photo_view >=0.4.0 which requires Flutter SDK version >=1.5.9-pre.94 <2.0.0, version solving failed.   pub get failed (1) Process finished with exit code 1

### ISSUE THREAD

**Issue by emailsubjekt** [renancaraujo/photo_view#154]
All I did was added   photo_view: ^0.4.0 to pubspec.yaml and this is what I got 

The current Flutter SDK version is 1.5.4-hotfix.2.

Because your_app depends on photo_view >=0.4.0 which requires Flutter SDK version >=1.5.9-pre.94 <2.0.0, version solving failed.

pub get failed (1)
Process finished with exit code 1

**Comment by renancaraujo** [comment]
Change pphoto_view version for 0.3.3 or use Fluter channel beta.
Read the [releases page](https://github.com/renancaraujo/photo_view/releases/tag/0.4.0).
