### ISSUE TITLE
Saving zoomed image?

### ISSUE THREAD

**Issue by monderwa** [renancaraujo/photo_view#156]
HI,

Thanks for providing the library, it looks great! I intend to use the Inline PhotoView, but I would like to save the zoomed/rotated image when the user is finished. Is that possible?

/Martijn

**Comment by StefanLobbenmeier** [comment]
I hope its not rude to show you another repository, but to me it sounds like you are rather looking for this: https://github.com/hnvn/flutter_image_cropper, otherwise, please elaborate on what your usecase is.

**Comment by monderwa** [comment]
Hi Stefan, thanks for replying. Indeed, I was planning to use that, but I discovered that the library contains only one function ('_cropImage()') and it shows the entire window , so including the two bars at the bottom (for zoom/rotate/crop) and the X, 'edit photo', and the tick. I want to include the functionality in my own widget directly. Probably, I can modify the plugin and extract the functionality, but it seems that this is quite basic functionality that most likely already exists. Do you have any ideas?

**Comment by StefanLobbenmeier** [comment]
The only other library I know that might fit is this one: https://pub.dartlang.org/packages/image_crop, but I guess feel free to fork this one and add the save functionality, you can use the other libararies as a reference for that.

**Comment by monderwa** [comment]
Thanks! Image_crop was indeed my alternative. In the end, I used ZoomableWidget from https://github.com/mchome/flutter_advanced_networkimage, combined with https://github.com/parth181195/flutter_widget_to_image. That suffices for me for now.
