### ISSUE TITLE
change the magnification level when doubleTap

### ISSUE THREAD

**Issue by WeiKnowi** [renancaraujo/photo_view#158]
How can I change the magnification level ,when doubleTap the image.I mean times,not your level.

**Comment by renancaraujo** [comment]
You can check the option `scaleStateCycle` where you can define how Photo View respond to double taps. Links: 
https://pub.dev/documentation/photo_view/0.3.3/photo_view/PhotoView/scaleStateCycle.html
https://pub.dev/documentation/photo_view/0.3.3/photo_view/ScaleStateCycle.html

**Comment by renancaraujo** [comment]
I'm closing this issue for now. If you consider your question not solved, feel free to reopen it and let's move forward with the discussion.
