### ISSUE TITLE
Zooming in on specific position(x, y) in a zoomed image (moving the screen).

### ISSUE THREAD

**Issue by YoungRan2** [renancaraujo/photo_view#160]
I want to see on the screen by moving to the desired coordinates from the enlarged image only by coding without touching the screen by hand. 

Using the code below, the image itself has moved.
(the starting point of the picture has moved... )

PhotoViewController _TouchScaleController;
_TouchScaleController.position = offset(130, -70);

![Screenshot_2019-07-11-10-32-30](https://user-images.githubusercontent.com/48503958/61015730-d7737c00-a3c7-11e9-8b95-625ea2303f12.png)

Regardless of whether the image is enlarged or not enlarged, I want the left and right ends to stick at the end of the screen.

**Comment by renancaraujo** [comment]
Looks like a bug, the widget should clamp position even if set via controller.

**Comment by renancaraujo** [comment]
Fixed on #208
