### ISSUE TITLE
High resolution image zoom result in black screen [BUG]

### ISSUE THREAD

**Issue by liushiqi9** [renancaraujo/photo_view#162]
**Describe the bug**
I am running the demo with one of my high resolution image. And I can see the image, even zoom it a little bit, but after I zoom it to certain ratio, it will black out, and when it zoom back, it will show the picture again. I think this is a bug.

**To Reproduce**
1. Run example code with the image I uploaded.
2. zoom the image.

**What is the current behavior?**
It will be fine at first, but after zoomming it to approximatly 1.2x, it will result on black screen and show nothing. 
**Expected behavior**
zoom works until it meet max_ratio.

**Image**
![high_resolution](https://user-images.githubusercontent.com/6860451/61188862-033c7d80-a6b8-11e9-9724-658efb909d3d.jpg)

**Comment by RukaiJohn** [comment]
I'm having the same issue. Did you figure out how to solve this?

**Comment by renancaraujo** [comment]
Yes, this is a problem with flutter itself, looks like every hi-res image when scaled up just disappears. Even without photo view. I'm looking directly into flutter engine code to see what happened but no success so far. OP has opened an issue on main flutter repo: flutter/flutter#36191

**Comment by renancaraujo** [comment]
Looks like the problem has been solved on flutter 1.7. 

I will close the issue for now,  If you consider your question not solved, feel free to reopen it and let's move forward with the discussion.

**Comment by renancaraujo** [comment]
For whoever reading this, the problem was not completely solved. We have a hotfix here: https://github.com/flutter/flutter/issues/36191#issuecomment-542537103
