### ISSUE TITLE
[BUG] Enter landscape cuts image

### ISSUE THREAD

**Issue by ultracheb** [renancaraujo/photo_view#163]
**Describe the bug**
When you entering screen with image it looks good, when you rotate device to landscape mode image becomes cut with no ability to see whole image. After rotation image must reset it size.

**To Reproduce**
1. Enter the following screen https://gist.github.com/ultracheb/0ee41ff796884a1e3f84c585e53b1830
2. Rotate device to landscape mode

**What is the current behavior?**
Image is cutted.

**Expected behavior**
Image must reset/recalculate it boundaries to fit the screen.

**Screenshots**
here are screenshots, affect image and video to reproduce this bug
https://1drv.ms/f/s!AlNXJxCRAUKSgap_7aVhGB1A9__6_Q

**Is this a *feature* or report a *bug*?**
bug

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. The output of flutter doctor can help too. ** 
Example https://gist.github.com/ultracheb/0ee41ff796884a1e3f84c585e53b1830
Output of flutter doctor https://gist.github.com/ultracheb/94b2e0fb9651f43a7b36ee65563f3472

**Which versions of Flutter/Photo View, and which browser / OS are affected by this issue? Did this work in previous versions of Photo View?**
flutter 1.7.8+hotfix.3
photo_view 0.4.2
windows 10

**Additional context**
If you open this screen straight in landscape mode it will looks good.

**Comment by renancaraujo** [comment]
@ultracheb Sorry for the huge delay. Tackled on #207.

**Comment by renancaraujo** [comment]
Included on 0.8.1

**Comment by ultracheb** [comment]
Yeah, fixed
