### ISSUE TITLE
Text in image can't read properly 

### ISSUE THREAD

**Issue by Adilkp796** [renancaraujo/photo_view#166]
![Screenshot_20190730-134427 (1)](https://user-images.githubusercontent.com/32359119/62113389-254a1880-b2d2-11e9-9543-9b3a7e593602.png)

Hello guys . is there any  solution for this ?

**Comment by renancaraujo** [comment]
Yeah, posting some more details about your case (like code or what you are trying to show inside photo view) would be a great start.
