### ISSUE TITLE
Exit gallery gesture

### ISSUE THREAD

**Issue by mabuelhagag** [renancaraujo/photo_view#170]
**Is your feature request related to a problem? Please describe.**
I don't seem to find a gesture that exit the gallery. Devices that doesn't have a back button could use a gesture like that.[...]

**Describe the solution you'd like**
A Swipe Up gesture to exit the gallery mode .

**Describe alternatives you've considered**
A flat button widget to exit the view.

**Comment by renancaraujo** [comment]
Dupe of #167.
