### ISSUE TITLE
Hero's `createRectTween`

### ISSUE THREAD

**Issue by hugocbpassos** [renancaraujo/photo_view#175]
I have to set a custom `createRectTween` to `PhotoView`'s Hero.

 Currently, two attributes of `PhotoViewImageWrapper` are exclusively Hero's parameters: `heroTag` and `transitionOnUserGestures`. At this point, I think there should be a property called `heroAttributes`, which will lighten `PhotoViewImageWrapper`'s parameters and also let more clear which parameters are Hero-related (I mean, `createRectTween` as a parameter of a `PhotoView` may seen completely out of place).

I can submit a PR with all of these improvements, but breaking changes are going to emerge, so I need your approval to make sure I won't waste my time.

**Comment by renancaraujo** [comment]
Absolutely, go for it.

**Comment by renancaraujo** [comment]
Tackle'd.
