### ISSUE TITLE
[BUG] PhotoView without fixed size

### ISSUE THREAD

**Issue by p02diada** [renancaraujo/photo_view#176]
**Describe the bug**
I can not create a PhotoView whithout a parent container fixed height. Is it posible?

I am getting the following error:

```
RenderCustomSingleChildLayoutBox object was given an infinite size during layout.
This probably means that it is a render object that tries to be as big as possible, but it was put
inside another render object that allows its children to pick their own size.
```

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.13.6 17G7024, locale es-ES)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.3)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by renancaraujo** [comment]
Could you provide more code regarding where `PhotoView` is instantiated?

Just by looking at this message I can guess that the problem is related to another woidget. Are you using `PhotoView.customChild` ?

**Comment by dpedrinha** [comment]
I've the same question. I need the `PhotoView.customChild` to be built using the parent's size. But it requires the `childSize`.

Here's an example: 
```
class ImageZoomPage extends StatelessWidget {
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('title'),
      ),
      body: PhotoView.customChild(
        child: Container(
          child: Stack(
            //overflow: Overflow.clip,
            fit: StackFit.expand,
            children: <Widget>[
              Image(
                image: AssetImage('images/image1}'),
              ),
              Image(
                image: AssetImage('images/image2'),
              ),
              Image(
                image: AssetImage('images/image3'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

Since I need 3 overlapping images I need to use customChild. But how can I set the childSize? I need it to fill its parent. 

Any solution for that?

**Comment by renancaraujo** [comment]
@dpedrinha  That is not possible right now because of the very original use case for photo view: Scale images in a container with a known size (very often the screen size). To do that photo view has to know both the size for the container and child. to compute the right scale applied to children. 

You can wrap everything in a layout builder and then set the size the biggest size fromthe provided constraints to the container inside photo view.

**Comment by dpedrinha** [comment]
Yes that's more or less what I did.
But this solution would work in all scenarios including full screen so it's something to keep in mind.

**Comment by GiacomoK** [comment]
@renancaraujo can you please do me an example (or explain better cause I did not understand) what you mean with:

"You can wrap everything in a layout builder and then set the size the biggest size fromthe provided constraints to the container inside photo view."

Thank you

**Comment by renancaraujo** [comment]
@GiacomoK I mean, the code would be like this:
```dart
class ImageZoomPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('title'),
      ),
      body: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
          return PhotoView.customChild(
            childSize: constraints.biggest,
            child: Container(
              child: Stack(
                //overflow: Overflow.clip,
                fit: StackFit.expand,
                children: <Widget>[
                  Image(
                    image: AssetImage('images/image1}'),
                  ),
                  Image(
                    image: AssetImage('images/image2'),
                  ),
                  Image(
                    image: AssetImage('images/image3'),
                  ),
                ],
              ),
            ),
          );
        },
      ),
    );
  }
}

```

**Comment by renancaraujo** [comment]
@dpedrinha Just opened a new issue regarding `childSize` here: #199

**Comment by renancaraujo** [comment]
Since there is no response from the issue creator I am closing this issue for now, If you got any new insight regarding this problem, feel free to retake the discussion.
