### ISSUE TITLE
 When will you update the version?

### ISSUE THREAD

**Issue by tichaun** [renancaraujo/photo_view#179]
When I use it, I encounter the following problems：

The current Flutter SDK version is 1.5.4-hotfix.2.
Because imgsee_show depends on photo_view >=0.4.0 which requires Flutter SDK version >=1.5.9-pre.94 <2.0.0, version solving failed.

**Comment by phelipepalte** [comment]
Same problem

**Comment by tichaun** [comment]
> 同样的问题

Have you solved it yet? Or wait for the author to update

**Comment by renancaraujo** [comment]
PhotoView is stable compatible. The current version on the stable channel is `v1.7.8+hotfix.4`. I'm running this version of PhotoView on some of my apps and there is no major version incompatibility. I would suggest you run flutter upgrade or downgrade PhotoView to 0.3.3 (the last flutter 1.5 version compatible). 


For more info, check this release note: https://github.com/renancaraujo/photo_view/releases/tag/0.4.1
