### ISSUE TITLE
[Help] How can i use single tap to dismiss photo_view dialog

### ISSUE THREAD

**Issue by Karthus1110** [renancaraujo/photo_view#182]
I use photo view like this, i don't find a correct way to dismiss this photo view
showDialog(
                            context: context,
                            builder: (_) {
                              return PhotoView(
                                imageProvider: NetworkImage(
                                    _imageURL,
                                    headers: _httpHeaders),
                              );
                            });

**Comment by Karthus1110** [comment]
@davewang @AlexVegner @memo4mj @SocratesDz 
anybody can give some advise?

**Comment by renancaraujo** [comment]
Have you tried to wrap it in a [GestureDetector](https://api.flutter.dev/flutter/widgets/GestureDetector-class.html) with an `ontap`callback?

**Comment by Karthus1110** [comment]
@renancaraujo  I have tried but it's no use

**Comment by renancaraujo** [comment]
The [constructor](https://pub.dev/documentation/photo_view/latest/photo_view/PhotoView/PhotoView.html) has an `onTapUp` and onTapDown` opotions. Those can help you perhaps?

**Comment by Karthus1110** [comment]
@renancaraujo  I had tried this too.It is ambiguity when two fingers to zoom image may cause dismiss

**Comment by wapchief** [comment]
mark

**Comment by renancaraujo** [comment]
Related to #172 and #167

**Comment by wapchief** [comment]
Manually add a close button, can be solved

**Comment by omishah** [comment]
You can use with Hero() and single touch on photoview will dismiss view automatically.

**Comment by renancaraujo** [comment]
Added an example for that on the example app. 

![ontap](https://user-images.githubusercontent.com/6718144/69331862-67b2af00-0c4d-11ea-8573-bfe057c04dcb.gif)

**Comment by ssbaval** [comment]
One touch example to close the PhotoView that needs to have PINCH/RESIZE support  doesnt work if wrapped in a dialog and using PhotoView.customChild  - when trying to pinch to resize a small custom ICON (i.e an IconData) - the dialog closes

 i.e :

```

    showDialog(    
        context: context,
        builder: (context) {
          return OneTapWrapper(
            container: container,
          );
        });


```
```
class OneTapWrapper extends StatelessWidget {
  const OneTapWrapper({
    this.container,
  });

  final Widget container;

  @override
  Widget build(BuildContext context) {
    return Container(
      constraints: BoxConstraints.expand(
        height: MediaQuery.of(context).size.height,
      ),
      child: GestureDetector(
          onTapDown: (_) {
            Navigator.pop(context);
          },
          child: PhotoView.customChild(
            customSize: Size(1000, 1000),
            child: container,
            tightMode: true,
            enableRotation: true,
            backgroundDecoration: BoxDecoration(color: Colors.black54),
          )),
    );
  }
```
