### ISSUE TITLE
How do I disable Zoomable feature and set fit parameter

### ISSUE THREAD

**Issue by Milansu** [renancaraujo/photo_view#187]
Currently having an issue when loading 4k + images.
This library is the only one that loads it somehow...
But I just want to have the static image without zoomable feature, how can I achieve this?

**Comment by Milansu** [comment]
more about it on : 
`https://stackoverflow.com/questions/58336197/rendering-4000px-images`

**Comment by renancaraujo** [comment]
The answer is not the best approach.
```
IgnorePointer(
  child: PhotoView(
    imageProvider: ...
    initialScale: PhotoViewComputedScale.contained,
  ),
)
```

**Comment by Milansu** [comment]
@renancaraujo That worked perfectly. thank you
