### ISSUE TITLE
[BUG][Hero Animation]Detail view displays not smoothly when working with NetworkImage

### ISSUE THREAD

**Issue by ghostfox911** [renancaraujo/photo_view#191]
**Describe the bug**
Detail view displays not smoothly when working with NetworkImage.

**Environment**
- flutter_windows_v1.9.1+hotfix.4-stable
- photo_view 0.5.0

**To Reproduce**
- Run the example provided here: photo_view/example/lib/screens/examples/hero_example.dart
- In the main view tap on the 5th item 'Hero animation'.
- In the 'Hero Example' view tap on the photo.
- The image fills screen with smooth animation in the detail view.
- Changed AssetImage("assets/large-image.jpg") to NetworkImage(
                'https://tse2-mm.cn.bing.net/th?id=OIP.eJF_3NqUlhvmTK52ualvngHaE8&w=300&h=190&c=7&o=5&pid=1.7') in hero_example.dart at line 24.
- Changed Image.asset("assets/large-image.jpg", width: 150.0) to Image.network(
                'https://tse2-mm.cn.bing.net/th?id=OIP.eJF_3NqUlhvmTK52ualvngHaE8&w=300&h=190&c=7&o=5&pid=1.7', width: 150.0) in hero_example.dart at line 31.
- Performs hot reload.
- In the 'Hero Example' view tap on the photo again.              

**What is the current behavior?**
The image fills screen with non-smooth animation in the detail view. Looks like the image scales to a size and stops for milliseconds and scales to the final size.

**Expected behavior**
The image can fill the screen with smooth animation just like AssetImage does.

**Screenshots**
NA

**Is this a *feature* or report a *bug*?**
Bug report.

**Comment by renancaraujo** [comment]
Flutter doesn't cache all network images. As [docs say](https://pub.dev/documentation/photo_view/latest/photo_view/PhotoView-class.html): "To use within a hero animation, specify heroAttributes. When heroAttributes is specified, t**he image provider retrieval process should be sync**."

You can use cached_network_image  https://flutter.dev/docs/cookbook/images/cached-images
