### ISSUE TITLE
[BUG]Unable to load asset:

### ISSUE THREAD

**Issue by welldone217** [renancaraujo/photo_view#193]
**Describe the bug**
 `
════════ Exception caught by image resource service ════════════════════════════════════════════════
The following assertion was thrown resolving an image codec:
Unable to load asset: /storage/emulated/0/Android/data/top.tangh.app.kftong/files/Pictures/scaled_magazine-unlock-01-2.3.2272-95E6DCF7A83E5CE68CB43F3EF00D91A2.jpg

When the exception was thrown, this was the stack: 
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:464:44)
<asynchronous suspension>
#2      AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:449:14)
...
Image provider: AssetImage(bundle: null, name: "/storage/emulated/0/Android/data/top.tangh.app.kftong/files/Pictures/scaled_magazine-unlock-01-2.3.2272-95E6DCF7A83E5CE68CB43F3EF00D91A2.jpg")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#7e33a(), name: "/storage/emulated/0/Android/data/top.tangh.app.kftong/files/Pictures/scaled_magazine-unlock-01-2.3.2272-95E6DCF7A83E5CE68CB43F3EF00D91A2.jpg", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════`

**To Reproduce**
 

**What is the current behavior?**

`

GestureDetector(
      onTap: () {
        Navigator.push(
            context,
            MaterialPageRoute(
              fullscreenDialog: true,
              builder: (BuildContext context) => ViewImage(
                image: _image.path,
                onDeletePressed: () {
                  Navigator.of(context).pop(_index);
                },
              ),
            ))})

`

**Expected behavior**

 ` 

Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,
      floatingActionButton: FloatingActionButton(
        onPressed: widget.onDeletePressed,
        child: Icon(Icons.delete_forever, size: 36.0),
        backgroundColor: Colors.orange,
      ),
      body: Center(
          child: GestureDetector(
        onTap: () {
//          Navigator.pop(context);
          Navigator.of(context).pop(-1);
        },
        child: PhotoView(
          imageProvider: AssetImage(widget.image),
//          loadingChild: Center(
//            child: Container(
//              child: Text(_image),
//            ),
//          ),
        ),
      )),
    );
  }`

**Screenshots**

**Is this a *feature* or report a *bug*?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. The output of flutter doctor can help too. **

**What is the expected behavior?**

**Which versions of Flutter/Photo View, and which browser / OS are affected by this issue? Did this work in previous versions of Photo View?**
C:\game\kftong>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.18362.418], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

• No issues found!

  photo_view:  ^0.6.0

**Additional context**

**Comment by welldone217** [comment]
it is not working with hot reload  but work hot restart. if build a release version and install .this not working .

**Comment by renancaraujo** [comment]
It looks like an asset bundling problem. Make sure all assets are mapped correctly and the asset bundle is defined when instantiating photo view. https://github.com/flutter/flutter/issues/18820
