### ISSUE TITLE
How do i make background as Transparent/White color

### ISSUE THREAD

**Issue by mdzafar3194** [renancaraujo/photo_view#196]
Hi, i am newbie into flutter and i have added `PhotoView` in my application only to zoom in and zoom out of `NetworkImage` and working fine.

After image downloaded, how to make remaining background white/transparent?
Any help would be appreciated,
Thanks..

**Comment by renancaraujo** [comment]
Taking usage on readme as sample, this makes the background transparent:

```dart
@override
Widget build(BuildContext context) {
  return Container(
    child: PhotoView(
      imageProvider: AssetImage("assets/large-image.jpg"),
      backgroundDecoration: BoxDecoration(color: Colors.transparent),
    )
  );
}
```
