### ISSUE TITLE
Make childSize optional on customChild cosntructor.

### ISSUE THREAD

**Issue by renancaraujo** [renancaraujo/photo_view#199]
We can assume constaints.biggest as size from `LayoutBuilder` when child size is absent. 
Related: #176

**Comment by dpedrinha** [comment]
Is it already implemented?

**Comment by renancaraujo** [comment]
Not it is @dpedrinha. Tacled on #210

**Comment by dpedrinha** [comment]
#210 isn't clear on what it changed.

**Comment by renancaraujo** [comment]
@dpedrinha Does exactly what says in the issue: We can assume `constaints.biggest` as size from LayoutBuilder when child size is absent.
