### ISSUE TITLE
How can I load the images not in assets

### ISSUE THREAD

**Issue by winsonet** [renancaraujo/photo_view#202]
it seems the photo_view just can load the images from flutter assets, but I want to load the images created by myself and put into the cache folder, the file path will like below:
```
/data/user/0/com.myapp.mobile/cache/photo_3435/20945_20191111084336_1.jpg
```
it will show below error:
```
Unable to load asset: /data/user/0/com.myapp.mobile/app_flutter/photo_3435/20945_20191111084336_1.jpg
```

**Comment by renancaraujo** [comment]
The same way you would load this image to show on a `Image` widget. 
For files, use `FileImage`. Learn more: 
https://api.flutter.dev/flutter/painting/FileImage-class.html
https://api.flutter.dev/flutter/dart-io/File-class.html
