### ISSUE TITLE
[BUG] Gallery PhotoViewHeroAttributes

### ISSUE THREAD

**Issue by QueMarmota** [renancaraujo/photo_view#204]
**Describe the bug**
Image removed from list of image when you back from gallery view.

**To Reproduce**
1- Select the first image from the list of images.
2- In the gallery view scroll till the last image.
3- Back to the list of images 
4- The first image that was selected in step 1 its been remove.

**Expected behavior**
Keep the original list of images after gallery view.

**Screenshots**
[http://imgurl.me/image/hPUeF](url)

**Which versions of Flutter/Photo View, and which browser / OS are affected by this issue? Did this work in previous versions of Photo View?**
  photo_view: ^0.7.0
 Android 9/10

**Additional context**
My temporary solution was to avoid the hero widget and the PhotoViewHeroAttributes that it seems to be the problem.
![issue_photo_view](https://user-images.githubusercontent.com/15443285/68696417-92608180-0542-11ea-89a5-d46f181ff2a7.gif)

**Comment by renancaraujo** [comment]
Looks like #178
