### ISSUE TITLE
Galllery images with gridview ..

### ISSUE THREAD

**Issue by CarolineJenita** [renancaraujo/photo_view#213]
How to add grid view and display multiple images in gridview, so that it may able to zoom and scroll ..

Thanks in advance.

**Comment by renancaraujo** [comment]
@CarolineJenita You can do that by evolving every grid node with a `PhotoViewGestureDetectorScope`.

```dart
// ...
            PhotoViewGestureDetectorScope(
              axis: Axis.vertical, // or horizontal if you grid scroll horizontally
              child: PhotoView(
                imageProvider: const AssetImage("assets/large-image.jpg"), // or any imageprovider you use
              ),
            );
// ...
```

**Comment by renancaraujo** [comment]
Any update on this? I will close this issue for now. If you consider your question not solved, feel free to reopen it and let's move forward with the discussion.

**Comment by TugrulhanCinar** [comment]
> @CarolineJenita You can do that by evolving every grid node with a `PhotoViewGestureDetectorScope`.
> 
> ```dart
> // ...
>             PhotoViewGestureDetectorScope(
>               axis: Axis.vertical, // or horizontal if you grid scroll horizontally
>               child: PhotoView(
>                 tightMode: true,
>                 imageProvider: const AssetImage("assets/large-image.jpg"), // or any imageprovider you use
>               ),
>             );
> // ...
> ```
Thanks for the answer, it works. But how to change current assets images ?
