### ISSUE TITLE
Issue with PageController

### ISSUE THREAD

**Issue by davbaron** [renancaraujo/photo_view#214]
First of all, thank you for this wonderful add-in - it is exactly what I was looking for.  

I am having a small issue with the gallery's PageController.  Besides allowing my users to swipe between photos in a gallery I am providing buttons for them to 'go to next photo' or 'go to previous photo'.  I created/instantiated/attached the pageController and 'jumpToPage' works perfectly.  However 'animateToPage' does not ever 'animate'.  It simply 'jumps'.  Regardless of how large the Duration is, it jumps immediately.  Is this expected behavior?

**Comment by renancaraujo** [comment]
PageController used here is the same as used in PageView and PhotoView only passes it to PageView. If any behavior is different than a pageview would have in the same context, so there is a bug. Would you mind to see if a pageview in the same place of PhotoViewGallery hast this behavior? You can also create a gist for easy reproduction of your issue, so there we can figure if it is an issue with PhotoView or the framework.

**Comment by davbaron** [comment]
As I was creating the gist, I noticed that the 'Duration' was 2000 MICROseconds... not MILLIseconds!  I must have typed "M I" and then 'intellisense' took over and suggested microseconds, which I accepted... and didn't give a second thought to!  Once I changed the units to milliseconds just now it all works perfectly.  Thank you again @renancaraujo !

**Comment by renancaraujo** [comment]
Hahaha, I'm happy you figured it out, thanks.
