### ISSUE TITLE
Accept any image

### ISSUE THREAD

**Issue by cjarman** [renancaraujo/photo_view#218]
It seems that it not possible to load an image using a FileImage or MemoryImage provider.

An AssetImage or NetworkImage ImageProvider functions as expected.

I've test pulling an image from both a FileImage and MemoryImage to assign to standard Flutter image, so I know the FieImage or MemoryImage is good. 

See https://stackoverflow.com/questions/59043936/photoview-flutter-imageprovider-implementation-from-file-or-from-memory

**Comment by renancaraujo** [comment]
Looks like you got to solve your problem.

**Comment by renancaraujo** [comment]
@cjarman Any update on this? I will close this issue for now. If you consider your question not solved, feel free to reopen it and let's move forward with the discussion.
