### ISSUE TITLE
PhotoViewGallery does not switch image sometimes and the onTapUp callback dose not run.

### ISSUE THREAD

**Issue by ShshyDevooo** [renancaraujo/photo_view#223]
PhotoViewGallery does not scroll sometime and the onTapUp callback dose not run.

**What is the current behavior?**
When i am scrolling the gallery horizontal to switch the image , the gallery does not response.  I set onTapUp callback to the options, but the tapup callback does not run.

Versions:
photo_view  0.9.0
OS:Android ,have not test ios yet
Flutter:Flutter 1.9.1+hotfix.6

I am using flutter_advanced_networkimage  as the imageprovider , is it related?

**Comment by ShshyDevooo** [comment]
![device-2019-12-05-102825_2](https://user-images.githubusercontent.com/9620338/70199483-c5b2bc80-174c-11ea-96e4-b7ecc8fa4954.gif)

**Comment by ShshyDevooo** [comment]
The example has the same problem on my device too.

![device-2019-12-05-113757](https://user-images.githubusercontent.com/9620338/70202211-f6e2bb00-1753-11ea-88bc-88730bd06ee5.gif)

**Comment by shiwenbin770** [comment]
me too! Did you solve it?

**Comment by shiwenbin770** [comment]
After I upgraded the flutter version to 1.12.13+hotfix.5, This problem seems to be solved。

**Comment by renancaraujo** [comment]
I couldn't find the root cause for this, must be nin the framework. A diferent approach for the gallery ahs to be made.

**Comment by KinedYK** [comment]
I also encountered the same problem!

**Comment by DevKhalyd** [comment]
Mee too :(

**Comment by akbarraihan** [comment]
Anyone solve this issue?

**Comment by renancaraujo** [comment]
I shall ask any of you to test the code on #266 for the gesture detection.

**Comment by rodrigosakai** [comment]
Same issue here, no solutions yet? :( Or alternatives? Pardon me if I'm mistaken, but I haven't found any similar package.

**Comment by GabrielBottari** [comment]
Issue still persists with the latest dev version of flutter and photo_view (hooked up to git).

**Comment by woodstream** [comment]
When update to the latest master version of flutter, the same problem appear.

**Comment by xx-li** [comment]
I also encountered the same problem!

**Comment by renancaraujo** [comment]
For further discussions about this, check #304 and #293

**Comment by IMohamedBassam** [comment]
till now they didn't fix the issue,
I suspect it is related to the image dimensions (height and width).
either u use PhotoViewGalleryPageOptions.customChild as a builder, but then you need to manually double tap to zoom in, by using gestureDetector or inkwell,
or try to identify fixed customSize property inside the PhotoViewGallery.builder
