### ISSUE TITLE
[BUG] single finger swipe triggering PhotoViewScaleState.zoomedOut

### ISSUE THREAD

**Issue by blaneyneil** [renancaraujo/photo_view#227]
after setting up a scaleState listener, via the standard method:

`_scaleStateController = PhotoViewScaleStateController()..outputScaleStateStream.listen(_photoStateListener);`

```
PhotoView(
      scaleStateController: _scaleStateController,
),

```

a single finger swipe (as in a gesture someone would make if they were trying to swipe to another card) in any direction and or any distance is triggering this from the listener:

```
flutter: val = PhotoViewScaleState.zoomedOut
flutter: val = PhotoViewScaleState.initial
```

which means that if you're acting on a zoom (eg, hiding/showing a menu, changing bg color, etc) all of those actions will toggle upon the false zoom.  resulting in blinks, flashes, etc.

this is for iOS using `photo_view: "^0.9.0"`

**Comment by renancaraujo** [comment]
Fixed on #267 

Thanks for pointing it out.
