### ISSUE TITLE
[BUG] PhotoViewGallery doesn't size images properly on Web

### ISSUE THREAD

**Issue by GabrielBottari** [renancaraujo/photo_view#230]
**Describe the bug**
When compiling on web, the PhotoViewGallery does an appropriate hero animation but once complete, the image size is way too small, which renders the controls unusable.

**To Reproduce**
Implement a PhotoViewGallery on web, and open it up with a hero animation.

**What is the current behavior?**
Once the hero animation completes, the size of the image is tiny.

**Expected behavior**
When setting the scale to contained, the image should be contained in the gallery.

**Screenshots**
![image](https://user-images.githubusercontent.com/28274198/70745701-5875cd00-1cf2-11ea-981b-b92dd0aec17b.png)

**Is this a *feature* or report a *bug*?**
Bug report

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. The output of flutter doctor can help too. **
![bug](https://user-images.githubusercontent.com/28274198/70746674-3f6e1b80-1cf4-11ea-87bb-8fb6fe830148.gif)

[√] Flutter (Channel master, v1.13.1-pre.95, on Microsoft Windows [Version 10.0.17763.678], locale en-CA)
    • Flutter version 1.13.1-pre.95 at C:\src\flutter
    • Framework revision ceab1248d0 (25 hours ago), 2019-12-11 11:03:21 -0800
    • Engine revision 12bf95fd49
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 8b8894648f)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Gabriel\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools

**Which versions of Flutter/Photo View, and which browser / OS are affected by this issue? Did this work in previous versions of Photo View?**
Flutter latest master channel
PhotoView 0.9.0

**Comment by Skquark** [comment]
I was gonna report the same bug too, works fine on mobile but on web (which was my primary target) it comes out tiny instead of full screen.  I tried to find some workarounds, but everything looks proper and made to expand full screen size.  What's interesting is when I scroll through some photos, I have one or two that do stay full size properly.  Awaiting a fix, I can help dig into your code and track it down if you want, but wouldn't be sure what to look for yet.

**Comment by renancaraujo** [comment]
PhotoView is stable-channel compatible. Since we have lots of work to do for basic support, web is not a priority right now. 
Although, that's a nice opportunity to become a contributor, feel free to open a PR.

**Comment by SimonAmpleman** [comment]
On my side, for now, I disabled the hero tag on the web, and I used a different url to avoid image caching that seems to be the source of the problem. Now the image size is correct, but scrolling doesn't work well, sometime it doesn't scroll, sometime yes, looks like it is using the "small image" size for the hit area even if now the image size is large ...

**Comment by Skquark** [comment]
To let you guys know, the problem seemed to fix itself out.  After the updates last view weeks (on the dev channel), it's working for me in the Web, now going to full size when enlarging to full screen.  Much nicer, now web compatible and looking good, even with the hero animation..
