### ISSUE TITLE
Does photo view support device orientation for rotation?

### ISSUE THREAD

**Issue by wobeng** [renancaraujo/photo_view#232]
Does photo view support device orientation for rotation?

**Comment by renancaraujo** [comment]
What do you mean by `device orientation for rotation`?  Is that the ability to rotate an image by rotating the phone?
It doesn't seem like a common feature.

**Comment by renancaraujo** [comment]
Since we got no answer for a while, im closing this issue for now. If there is any news on that, fell free to retake the discussion.

**Comment by rockingdice** [comment]
I think it's about to rotate a photo of landscape orientation if the device is on portrait mode, automatically.
