### ISSUE TITLE
MemoryImage, base64Decode Support

### ISSUE THREAD

**Issue by Classy-Bear** [renancaraujo/photo_view#240]
The following line gives a blank image
`imageProvider:MemoryImage(base64Decode('your encoded url image'))`

**Comment by renancaraujo** [comment]
Does that work with `Image` widget?

**Comment by Classy-Bear** [comment]
Yep the code works fine without the plugin. Do you need captions or snippet codes to this?

**Comment by renancaraujo** [comment]
Yep, that would help.

**Comment by renancaraujo** [comment]
Since this issue is quiet for some time, I will close it for now for repo cleanliness. If you wanna retake the discussion, feel free to open it again.
