### ISSUE TITLE
Gradle task assembleDebug failed with exit code

### ISSUE THREAD

**Issue by BedRockGx** [renancaraujo/photo_view#241]
../lib/src/core/photo_view_gesture_detector.dart:185:10: Error: The method 'dependOnInheritedWidgetOfExactType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/E:/flutter_1.9+/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'dependOnInheritedWidgetOfExactType'.
        .dependOnInheritedWidgetOfExactType<PhotoViewGestureDetectorScope>();

**Comment by jackryan9013** [comment]
got same issue today and can't find any solutions :(

Error: The method 'dependOnInheritedWidgetOfExactType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/E:/flutter_sdk/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'dependOnInheritedWidgetOfExactType'.
        context.dependOnInheritedWidgetOfExactType<InheritedInject<T>>();
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compiler failed on E:\Flutter_Workspace\flutter-states-rebuilder-tutorial-master\flutter-states-rebuilder-tutorial-master\lib\main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by renancaraujo** [comment]
Which versions of Flutter/Photo View, and which browser / OS are affected by this issue?

**Comment by renancaraujo** [comment]
It seems to be compatible with the current flutter version.

**Comment by BedRockGx** [comment]
OK, thank you. I can use it after I reduce the version
