### ISSUE TITLE
[BUG]FLutter Web: Controls hidden by Image on page "Controller Example"

### ISSUE THREAD

**Issue by winwisely99** [renancaraujo/photo_view#244]
Flutter Web is on the  Left
- The controls near the bottom are hidden by the Image !!
FLutter Desktop is on the  Right

![Screenshot 2020-01-08 at 14 14 09](https://user-images.githubusercontent.com/56028033/71980872-6c451e00-3221-11ea-9823-1109a291eaf8.png)

**Comment by renancaraujo** [comment]
Looks like a Flutter web issue, wont be a priority until flutter web comes to stable channel.
