### ISSUE TITLE
Possibility to remove the 'onDoubleTap' event.

### ISSUE THREAD

**Issue by mirkopoloni** [renancaraujo/photo_view#246]
Hello, first of all I'm quite new to flutter development so please sorry if I write something wrong or inaccurate.

**Is your feature request related to a problem? Please describe.**
I use your library with the `PhotoView.customChild` which contains some gestureDetectors widgets inside of it.
My problem right now is that when I click the gestureDetector widgets inside the child there is a 300ms delay due to the `onDoubleTap` param of the `PhotoViewGestureDetector`.
I searched in your code and online, it seems to be the standard way of handling it: https://github.com/flutter/flutter/issues/22950#issuecomment-429483326.

**Describe the solution you'd like**
In my case I do not really need the double tap event and it would be great if there would be the possibility to set the `onDoubleTap` param to null, in order to avoid the 300ms delay.
I already tried to achieve it but I think that at the moment is not possible, please correct me if I'm wrong.
Is it something possible or is too complicated? As I said I do not have a lot of experience with Flutter and Dart, just trying to learn it.

Thanks.

**Comment by renancaraujo** [comment]
Hello there,
Sorry for the late answer.

It looks like a real edge case here. We try to make PhotoView as much flexible as possible, but some features (like this one) would eventually make photoview a lot more complex and therefore more susceptible to bugs without a gain that justifies it. I would eprsonally fork photoview and remove all unecessary gesture detection.

**Comment by renancaraujo** [comment]
For organizational sake, I'm closing this issue for now, if there is any new qustion or info, feel free to retake the dicussion.

**Comment by Xgamefactory** [comment]
it would be nice to have a property like disableDoubleTap
