### ISSUE TITLE
forward ImageStreamListener onChunk so we can have progress bar

### ISSUE THREAD

**Issue by neckaros** [renancaraujo/photo_view#249]
**Is your feature request related to a problem? Please describe.**
if the image to be displayed is big the user has no idea of the progress

**Describe the solution you'd like**
we should either be notified by a callback of progress event from ImageStreamListener or we could have a loading child builder which give loadedbytes and expectedbytes

**Additional context**
Since May 2019 ImageStreamListener now has an onChunk event:
`class ImageStreamListener {
  /// Creates a new [ImageStreamListener].
  ///
  /// The [onImage] parameter must not be null.
  const ImageStreamListener(
    this.onImage, {
    this.onChunk,
    this.onError,
  }) : assert(onImage != null);`

this onChunk send an event of type **ImageChunkEvent** which holds 
cumulativeBytesLoaded and expectedTotalBytes

**Comment by renancaraujo** [comment]
Nice idea, wanna try to tackle it with a PR? That would be awesome.

**Comment by neckaros** [comment]
done on PR #250

**Comment by neckaros** [comment]
@renancaraujo will you merge it ?

**Comment by renancaraujo** [comment]
@neckaros Sorry, forgot to close it. It is not only merged, but also published on 0.9.2.

Thanks!
