### ISSUE TITLE
Is it possible to close screen with photo_view by vertical swipe like in Telegram?

### ISSUE THREAD

**Issue by emvaized** [renancaraujo/photo_view#265]
In Telegram app, when some photo is open in full screen, and you swipe vertically, photo collapses and follows your gesture smoothly until being returned to it's place on previous screen (somewhat like Hero animation).

Is it possible to achieve something similar using photo_view?
Thanks in advance!

**Comment by emvaized** [comment]
Maybe it's possible to achieve using Dismissible or Draggable somehow?

**Comment by renancaraujo** [comment]
Yep, we have an example of usage with a drag gesture [here](https://github.com/renancaraujo/photo_view/blob/master/example/lib/screens/examples/dialog_example.dart), but to achieve something like telegram you would probably use GestureDetector with drag and enable photoview tight mode. 

Also, check #172 for the discussion.

**Comment by emvaized** [comment]
> Yep, we have an example of usage with a drag gesture [here](https://github.com/renancaraujo/photo_view/blob/master/example/lib/screens/examples/dialog_example.dart), but to achieve something like telegram you would probably use GestureDetector with drag and enable photoview tight mode.
> 
> Also, check #172 for the discussion.
Thanks for your answer!

I've already seen this thread, but it's not exactly what I'm looking for..

I tried to open full screen alert as described [here](https://stackoverflow.com/questions/51908187/how-to-make-a-full-screen-dialog-in-flutter), wrap PhotoView in Draggable, and listen for OnDrag offset to close screen -- and it somehow works actually, but no animation if drag threshold was not reached (to return photo on its place), and if it's reached (to smoothly pull it back on previous page).

Maybe you can share some ideas? Here's what I'm currently on:

```
Offset _dragReleaseOffset = Offset.zero;

_offsetTween = Tween<Offset>(
      begin: _dragReleaseOffset,
      end: Offset.zero,
    );

var photoview = PhotoView(
    heroAttributes: PhotoViewHeroAttributes(tag: 'photo${index}'),
    imageProvider: CachedNetworkImageProvider(photoUrl),
);

return Draggable(
        axis: Axis.vertical,
        childWhenDragging: Container(),
        feedback: photoWidget,
        child: SlideTransition(
             position: _offsetTween.animate(controller),
             child: photoWidget,
          ),
        onDragEnd: (details) {
            setState(() {
                _dragReleaseOffset = details.offset;
                 controller.reset();
                 controller.forward();
             });
            if (details.offset.dy < -100) Navigator.of(context).pop();
        },
      ),
```

**Comment by emvaized** [comment]
Never mind, I found a Flutter package called [Extended_image](https://pub.flutter-io.cn/packages/extended_image/versions/0.5.1), which has Slide Out widget which does exactly what I want.

**Comment by temirfe** [comment]
> Never mind, I found a Flutter package called [Extended_image](https://pub.flutter-io.cn/packages/extended_image/versions/0.5.1), which has Slide Out widget which does exactly what I want.

I'm also trying it, but drag threshold is big, you have to try hard to Slide Out, in telegram you can close with easy slide, were you able to achieve it?

**Comment by renancaraujo** [comment]
Keep discussion about other packages in other repos.
