### ISSUE TITLE
[Question] How to work with network images?

### ISSUE THREAD

**Issue by omikolaj** [renancaraujo/photo_view#268]
Is it possible to use network images as ImageProvider's such as:

Widget build(BuildContext context) {
  return Container(
    child: PhotoView(
      imageProvider: Image.network(
         url
       ),
    )
  );
}
It isn't super clear from the documentation or the code. Any idea how I would take an image coming from the internet and use this library with it?

Thank you

**Comment by renancaraujo** [comment]
Yes, It is on readme and API doc.

**Comment by renancaraujo** [comment]
Also example app.
