### ISSUE TITLE
[BUG]mmap failed errno 12 Out of memory

### ISSUE THREAD

**Issue by yunzhouhua** [renancaraujo/photo_view#269]
`PhotoViewGallery.builder(
            pageController: _controller,
            itemCount: total,
            onPageChanged: (index) {
              setState(() {
                currentIndex = index;
              });
            },
            builder: (BuildContext context, int index) {
              ImageProvider provider;
              if (widget.imgList[index].startsWith('http')) {
                provider = NetworkImage(widget.imgList[index]);
              } else {
                provider = FileImage(File(widget.imgList[index]));
              }
              return PhotoViewGalleryPageOptions(
                  imageProvider: provider);
            }),`
when i load image in sdcard,for example Photo,not assets,it will crash

E/Adreno-GSL(14013): <gsl_memory_alloc_pure:2261>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
W/Adreno-GSL(14013): <sharedmem_gpuobj_alloc:2608>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
E/Adreno-GSL(14013): <gsl_memory_alloc_pure:2261>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
W/Adreno-GSL(14013): <sharedmem_gpuobj_alloc:2608>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
E/Adreno-GSL(14013): <gsl_memory_alloc_pure:2261>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
W/Adreno-GSL(14013): <sharedmem_gpuobj_alloc:2608>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
E/Adreno-GSL(14013): <gsl_memory_alloc_pure:2261>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.

**Comment by renancaraujo** [comment]
Does it have somethiung to do with photoview or the image provider?
