### ISSUE TITLE
network breaks down, the app will crash and get stuck when you click the picture

### ISSUE THREAD

**Issue by DNetORM** [renancaraujo/photo_view#274]
If the network breaks down, the app will crash and get stuck when you click the picture，The debugging found that it was caused by an exception thrown due to the download failure

**Comment by renancaraujo** [comment]
Not a photoview bug.

**Comment by DNetORM** [comment]
Maybe this is not the direct bug of photo view, but whether photo view can be used as a compatible network interruption scenario, so that the picture can still be clicked on, and it doesn't matter if it can't be displayed. For example, the app shouldn't crash instead of loading prompts all the time

**Comment by DNetORM** [comment]
like cached_network_image
