### ISSUE TITLE
network breaks down, the app will crash and get stuck when you click the picture

### ISSUE THREAD

**Issue by DNetORM** [renancaraujo/photo_view#275]
If the network breaks down, the app will crash and get stuck when you click the picture，The debugging found that it was caused by an exception thrown due to the download failure,
Maybe this is not the direct bug of photo view, but whether photo view can be used as a compatible network interruption scenario, so that the picture can still be clicked on, and it doesn't matter if it can't be displayed. For example, the app shouldn't crash instead of loading prompts all the time,When the image has been in loading mode, the user will realize that this is a network problem, just close it, at least the program will not crash

**Comment by zinwalin** [comment]
there's no way to close photo_view window when all pictures can't load.  it's a big issue.
