### ISSUE TITLE
Gallery component

### ISSUE THREAD

**Issue by renancaraujo** [renancaraujo/photo_view#28]
It is time to think about a gallery component, where swiping for the side edges of the screen changes to next/prev images

**Comment by calebisstupid** [comment]
I just created a PR with a very simple implementation of this for the project I am working on. If it gets merged, just create a PhotoGalleryView with an array of ImageProviders and it will generate a PageView of each image (using the PhotoViewInline widget) with left/right swiping between each image.

It can definitely be enhanced quite a bit, like some UI showing what image you are on; it is very barebones atm

**Comment by renancaraujo** [comment]
Thanks, I will look into that ASAP.

About UI elements, I think this could be easily implemented via Stack. Let's keep PhotoView with less concerns as possible.

**Comment by calebisstupid** [comment]
For sure; that makes sense. I made a point not to alter any existing code too, and just added a new file and class for my implementation.

**Comment by renancaraujo** [comment]
@calebisstupid Just tested out what you have been doing, great job there. I've made some considerations in the PR.

**Comment by kainecy** [comment]
How can i put multi `PhotoViewInline` into one Column/ListView? 
Should I waiting for the `Gallery component` or use some code like @renancaraujo 's PR

**Comment by renancaraujo** [comment]
After some time thinking about the questions raised on #31, I've addressed some of them in a different branch.

Keeping in mind that we should support every photo view feature in the gallery (such as hero animations) I've opened a new PR #35. 

![ezgif-4-44bb60fe8c2f](https://user-images.githubusercontent.com/6718144/46573612-2e967d00-c96e-11e8-9b9f-a70d5a62861d.gif)
