### ISSUE TITLE
real-time changes

### ISSUE THREAD

**Issue by 120011676** [renancaraujo/photo_view#280]
How much zoomed, how much rotated, center point moved

**Comment by renancaraujo** [comment]
You can check the[ examples app using controllers](https://github.com/renancaraujo/photo_view/blob/master/example/lib/screens/examples/controller_example.dart).

![](https://user-images.githubusercontent.com/6718144/56464051-3328fd00-63b7-11e9-9c4d-73b04f72a81e.gif)

**Comment by 120011676** [comment]
@renancaraujo tks,good
