### ISSUE TITLE
[BUG] Show SVG image -> Exception: Could not instantiate image codec

### ISSUE THREAD

**Issue by DVCStudioX** [renancaraujo/photo_view#290]
My code:
`Container(child: PhotoView(imageProvider: AssetImage('assets/abc.svg'))),` then it shows an error "Exception: Could not instantiate image codec."
have I missed anything?

**Comment by Grohden** [comment]
The readme states:
`It also can show any WIDGET instead of an image, such as Container, Text or a SVG.`
So.. the package doesn't support SVG, it only supports custom widgets which MAY render SVG images :/ ...
