### ISSUE TITLE
Hit Image Border Detector

### ISSUE THREAD

**Issue by winsonloh1998** [renancaraujo/photo_view#294]
**My Case**
I implemented **PhotoView** widget within the **PageView.builder** and i wanted to proceed to next/previous image when the zoomed-in image hit the border. Currently, i took the value of position **dx** to make a condition to detect the case (using controller), but this is not practical because one swipe action returns multiple times of **dx** value and also different speed and distance of the swipe action has different number of occurrence of **dx** value. 

**Solution/Features that I wanted**
 Is there a way that I can detect when the image is panned to its border/end side?

**Comment by renancaraujo** [comment]
The PhotoViewGallery does exactly that, you can see what we do on `PhotoViewGestureRecognizer`.
