### ISSUE TITLE
Progressive Image Loading

### ISSUE THREAD

**Issue by TinyDurk** [renancaraujo/photo_view#295]
If I want to load image without self loadingBuilder, but with progressive image loading like JPEG, how to do that job?

**Comment by TinyDurk** [comment]
I have resolved it. Using loadingBuilder to render a image with thumbnail url, then load original photo and replace the thumbnail image.

**Comment by ShahoodulHassan** [comment]
> I have resolved it. Using loadingBuilder to render a image with thumbnail url, then load original photo and replace the thumbnail image.

Code, please?
