### ISSUE TITLE
How to support FileImage？

### ISSUE THREAD

**Issue by YinHAHA** [renancaraujo/photo_view#297]
I want to show file image（FileImage），how should i do?
example:  /storage/emulated/0/Android/data/com.XXXX/files/Pictures/d0bf463d-07c9-487a-ba1d-02ede8161aee9165516036737135257.jpg

**Comment by renancaraujo** [comment]
Pass `FileImage` as `imageProvider`.

**Comment by cloudy-ninja** [comment]
@YinHAHA FileImage worked?
On my side, it isn't working
