### ISSUE TITLE
RenderRepaintBoundary.toImage() cannot get the image from PhotoView

### ISSUE THREAD

**Issue by RustFisher** [renancaraujo/photo_view#40]
Using `RepaintBoundary` with `GlobalKey` to take screenshot for `PhotoView` and output png file.

The output png file is only black. 

Could you pls post an example with `RepaintBoundary`?

**Comment by RustFisher** [comment]
It seems like relate to this issue https://github.com/flutter/flutter/issues/17687
My `flutter doctor`:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.10.1-pre.40, on Mac OS X 10.13.6 17G2307, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[!] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.28.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.

**Comment by RustFisher** [comment]
It is a flutter bug, not `PhotoView` bug.
> running the app with --enable-software-rendering this problem is not reproduced anymore.

close

**Comment by FangWW** [comment]
"flutter build apk"  --enable-software-rendering
How do I add this parameter ?

**Comment by RustFisher** [comment]
> "flutter build apk" --enable-software-rendering
> How do I add this parameter ?

Same problem. Don't know how to "--enable-software-rendering" while release apk.
