### ISSUE TITLE
start photo view gallery with specific image ..

### ISSUE THREAD

**Issue by sr1dh4r** [renancaraujo/photo_view#44]
Photo view gallery always starts from first index. Is there a way to use the gallery widget but start at say 5th image ? An example would be device gallery where we select an image and are able to swipe left right from there .. I tried looking at the code but I'm still wrapping my head around it so thought I'd check first :) Thanks !!

**Comment by dinhha** [comment]
You should use PageController and set initialPage for it

**Comment by sr1dh4r** [comment]
yup, just realised :) . Thanks a lot for the reply .. closing the issue!!
