### ISSUE TITLE
View image from camera or photo library 

### ISSUE THREAD

**Issue by leovu0703vn** [renancaraujo/photo_view#46]
Thank you for the awesome framework. I can use your app for the asset images and network images perfectly. However, in my app, I still need to zoom in and zoom out the image which is picked by user by the image_picker framework. I can access the Image from that framework , but I cant make it work for the imageProvider. Can you help me about this issue? 
Thank you.

**Comment by renancaraujo** [comment]
Since`ImagePicker.pickImage`  returns a `Future<File>`, you could use `FileImage` (an Image provder that reads file) as `imageProvider` in `PhotoView` constructor. 


An example:

```dart
import 'package:image_picker/image_picker.dart';
import 'package:photo_view/photo_view.dart';


class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  File _image;

  Future getImage() async {
    var image = await ImagePicker.pickImage(source: ImageSource.camera);

    setState(() {
      _image = image;
    });
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Image Picker Example'),
      ),
      body: new Center(
        child: _image == null
            ? new Text('No image selected.')
            : PhotoView(
                 imageProvider: FileImage(_image),
             )),
      ),
      floatingActionButton: new FloatingActionButton(
        onPressed: getImage,
        tooltip: 'Pick Image',
        child: new Icon(Icons.add_a_photo),
      ),
    );
  }
}
```

Read more about File Image here:  https://docs.flutter.io/flutter/painting/FileImage-class.html
