### ISSUE TITLE
Overlapping Image when used in Column

### ISSUE THREAD

**Issue by Purus** [renancaraujo/photo_view#47]
I have the below code to show a zoomable image and another widget below it.

When I zoom the image to a larger scale, the image overlaps the second widget below the container.

```
            return Column(
              children: <Widget>[
                Expanded(
                  child: Container(
                    height: 300.0,
                    margin: const EdgeInsets.symmetric(vertical: 20.0),
                    child: PhotoViewInline(
                      imageProvider: CachedNetworkImageProvider(
                        post.imageUrl,
                      ),
                    ),
                  ),
                ),
                getFeedWidget(),
              ],
            );
```

The second widget is visible over the zoomable image. Ideally, user should see only the zoomable image.

**Comment by renancaraujo** [comment]
You can use [ClipRect](https://docs.flutter.io/flutter/widgets/ClipRect-class.html) around Container to avoid that overlaping.

**Comment by Purus** [comment]
It works.. Thanks..

**Comment by PiN73** [comment]
Does it make sense to add example with ClipRect to readme?
