### ISSUE TITLE
Get position of touch with regard to image

### ISSUE THREAD

**Issue by rmkubala** [renancaraujo/photo_view#49]
I need to somehow get an information about the position where a user tapped relative to the image. In other words I need to know the click location with regard to the scaled and translated image, not the widget itself.
When I wrap the PhotoViewInline with GestureDetector, I'm able to get the position of the tap with regard to the widget. Now, I need to offset that tap position to get the x, y of the image where the touch occoured.

**Comment by renancaraujo** [comment]
I think it could be achieved with photoview's internal state exposition.

**Comment by rmkubala** [comment]
That is correct, only offset from top left corner and zoom level would be required.

This is a blocker in my project, do you think it is a quick enhancement or it will take some time?

**Comment by renancaraujo** [comment]
Since it has been very hard to find a time to work on photo view, I would advise you, for now, fork this project and expose `PhotoViewImageWrapper`'s state through `PhotoView` and `PhotoViewInline`.

**Comment by renancaraujo** [comment]
@ElTopo with the merge of #89, the photo view's internal state is exposed. This enable outside widgets access values such as `position` and scale and listen to its changes through a stream.

In order to achieve the exact behavior suggested in this issue, we need also some callbacks.

**Comment by renancaraujo** [comment]
This issue was solved long ago on #122 .
