### ISSUE TITLE
Please Support SVG 

### ISSUE THREAD

**Issue by HerrNiklasRaab** [renancaraujo/photo_view#51]
Currently using this plugin: https://pub.dartlang.org/packages/flutter_svg

**Comment by renancaraujo** [comment]
I think we should extract the zoomable widget to another package to let the user put anything instead of an image. I will think something regarding that.

**Comment by HerrNiklasRaab** [comment]
Hey great news :). Sorry that i cannot help at the moment, i am very very bussy. Otherwise, I would have made a Pull Request, days before.

**Comment by HerrNiklasRaab** [comment]
I think, we should defenetly make a new package only used for zooming any widgets. But i understand. What happens with photo_view, because the most sourcecode is in the zooming widget? Adding a new option to the constructor is against: https://en.wikipedia.org/wiki/Open%E2%80%93closed_principle

**Comment by renancaraujo** [comment]
`What happens with photo_view, because the most source code is in the zooming widget`
That is the problem with the new widget idea. 

What about a new constructor? 
```dart
PhotoView.customChild({
   child: YourWidget()
})
```
That would provide os ground to new festures, like 
```dart
PhotoView.foo({
   bar: value
})
```

**Comment by renancaraujo** [comment]
Just added the new constructor to the master.
```dart
PhotoView.customChild(
  child: Container(
    decoration: const BoxDecoration(color: Colors.lightGreenAccent),
    padding: const EdgeInsets.all(10.0),
    child: SvgPicture.asset(
      "assets/firefox.svg",
      height: 100.0,
    )
  ),
  childSize: const Size(220.0, 250.0),
),
```

There is a working example in the [`example app`](https://github.com/renancaraujo/photo_view/blob/d1b5665ffda6e18a546de6e21d67e53d939928b9/example/lib/screens/custom_child_examples.dart):

**Comment by renancaraujo** [comment]
Once I solve some issues that we have on the master, I will release it on 0.1.0 probably. Looking forward to finish it by the weekend.

**Comment by renancaraujo** [comment]
Just published the changes  [here](https://github.com/renancaraujo/photo_view/releases/tag/0.1.0). You can check a sample using SVG in the [example app](https://github.com/renancaraujo/photo_view/blob/0c538f05e2af9c312a0a7639073b19c3cfad50f3/example/lib/screens/custom_child_examples.dart#L45).

**Comment by HerrNiklasRaab** [comment]
Great, thanks a lot, this will take my app to a further level!

Renan <notifications@github.com> schrieb am Di. 27. Nov. 2018 um 23:21:

**Comment by renancaraujo** [comment]
@HerrNiklasRaab Nice! What a great opportunity to become a contributor, huh? 😁
