### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by sgon00** [renancaraujo/photo_view#6]
First, thank you very much for this widget. It's very helpful. I have some questions here. 

(1) I put it in a `Container` as shown in the example, but padding left and right does not work such as `padding: EdgeInsets.only(left: 10.0, right: 10.0),`. Is that possible to support padding? If it's not, it's OK. 

(2) I just want to zoom in a photo, but NOT zoom out. How can I restrict the zoom out action?  I tried to set `minScale: 0.0,` which is the default value, it does not do anything. I think `minScale: 0.0,` should restrict the zoom out action, otherwise what is the point of `minScale`? 

Thanks a lot. 

Edited:
Actually, padding left and right is kinda meaningless. You can simply ignore my first question.

**Comment by renancaraujo** [comment]
Scale is not an integer value. It multiplies the actual size of the image. So if you want to restrict zoom out, you should set minScale as 1

**Comment by sgon00** [comment]
@renancaraujo Thanks for your reply. Actually, you are right and I did try minScale as 1. But I didn't express my request correctly. Please let me re-describe my question (request) regarding restricting zoom out. This is actually what all other production apps that I used do:
(1) When the screen opens, the image scales to fit the screen's width. (regardless whether the image actual width is bigger or smaller than the screen's width). This is what this plugin does and it's correct.
(2) Restricting zoom out should restrict zoom out of the initial image size shown on the screen (thus not allowed to scale smaller than the screen's width).

I see the current behavior is:
miniScale will restrict zoom out of the image's actual width (size). That looks a little bit weird to me when the image actual size is much bigger than the screen's size. when I try to zoom out, it suddenly becomes very very big. 

Due to my limited English skill, I am not sure if you can understand what I mean. And I don't know if my request is easy to be achieved or not and don't know if this sounds good to you or not. 

Thanks.

**Comment by renancaraujo** [comment]
Yes, I see your point.
Actually, the plugin is oriented by those 4 values in the [PhotoViewScaleType](https://github.com/renancaraujo/photo_view/blob/master/lib/photo_view_scale_type.dart) enum: 
contained, covering, originalSize, zooming

Contained is when the image fits the screen by inside. To achieve that, photo_view scales (up or down) the image in the mount of the plugin. [(here are the lines)](https://github.com/renancaraujo/photo_view/blob/master/lib/photo_view_utils.dart#L46)

We shouldn't do this process if minScale has been specified.

Tagging this as a bug.

**Comment by sgon00** [comment]
Thanks a lot for the reply and quick action. Due to my limited English, I am sorry that actually I don't quiet understand how you are going to fix it in your last post. What I expect when `minScale` sets to 1.0:

(1) Regardless the image's original size, the image fits the screen. 
thus `image's width = screen's width.`
(2) The image can not scale down. Thus the minimum of the image's width is the screen's width. 

This is how other native apps do in my experience. Not sure if this is what you are going to change to.

**Comment by renancaraujo** [comment]
The `scale`value refers to the current factor which the images is multiplied. `1.0` isn't necessarily the image fitted to screen. That would be `screenWidth/imageWidth`. 
I think we should let the user pass a constant to min scale, as follows:
```dart
@override
Widget build(BuildContext context) {
  return new Container(
    child: new PhotoView(
      imageProvider: imageProvider,
      minScale: PhotoViewScale.contained,
      maxScale: PhotoViewScale.covered
    );
  );
}
```
I will try to work on this today, I will let you know when a PR is ready.

**Comment by Blakexx** [comment]
I was able to solve this issue by getting the dimensions of an image when it loads, then putting 
`MediaQuery.of(context).size.width/imageWidth` as the minScale and `4.0*MediaQuery.of(context).size.width/width` as the maxScale.

I got these dimensions with this block of code:

`pickedImage.image.resolve(new ImageConfiguration()).addListener((ImageInfo info, bool b){
                                    height = info.image.height*1.0;
                                    width = info.image.height*1.0;
                                  });`

**Comment by renancaraujo** [comment]
@sgon00 check # 9, now the airplane image example has the desired behavior.

**Comment by sgon00** [comment]
Hi, I am sorry to trouble you. Just one more question. Due to the issue #11, can I set something like `minScale: PhotoViewScaleBoundary.contained / 2` so that I can show the image completely, otherwise some images may lose their top and bottom parts. Thanks a lot.

**Comment by renancaraujo** [comment]
@sgon00  Yes you can use `*` and `/` operators to `PhotoViewScaleBoundary`
