### ISSUE TITLE
Need Dynamic PhotoViewGalleryPageOptions

### ISSUE THREAD

**Issue by venkatdreams** [renancaraujo/photo_view#63]
How to add Dynamic data in loop for PhotoViewGalleryPageOptions

**Comment by renancaraujo** [comment]
@venkatdreams I'm not sure if I understood what you meant. Could you give an example of how it could be used or refer to any widget/lib that has something similar?

**Comment by renancaraujo** [comment]
Due to the lack of answers, I will close it for now.

**Comment by dmazlum** [comment]
Hello,

I am stuck same subject Dynamic PhotoViewGalleryPageOptions. How to create dynamic fullscreen gallery from json.

**My loop**

`var subData = subcats.gallery;

    if (subcats != null) {
      var lengthOfList = subData.length;

      for (int i = 0; i < lengthOfList; i++) {
        Galleries subcat = subData[i];

        // Image URL
        var imageURL = "http://10.0.2.2:8081/gallery/" + subcat.photoName;

        var listItem = new Container(
            constraints: BoxConstraints.expand(
              height: MediaQuery.of(context).size.height,
            ),
            decoration: BoxDecoration(
              border: new Border.all(color: Colors.blueGrey[200]),
              boxShadow: [
                BoxShadow(
                  color: Colors.black12,
                  blurRadius: 10.0,
                )
              ],
            ),
            padding: const EdgeInsets.symmetric(horizontal: 5.0),
            child: GestureDetector(
              onTap: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => FullScreenWrapper(
                          imageProvider: NetworkImage(imageURL),
                          index: i,
                        ),
                  ),
                );
              },
              child: new CachedNetworkImage(
                imageUrl: imageURL,
                fit: BoxFit.cover,
                placeholder: (context, url) => new CircularProgressIndicator(),
                errorWidget: (context, url, error) => new Icon(
                      Icons.error,
                      color: Colors.red,
                    ),
              ),
            ));

        listElementWidgetList.add(listItem);
      }
    }`

`class FullScreenWrapper extends StatefulWidget {
  FullScreenWrapper({
    this.imageProvider,
    this.loadingChild,
    this.backgroundDecoration,
    this.minScale,
    this.maxScale,
    this.initialScale,
    this.basePosition = Alignment.center,
    this.index,
  }) : pageController = PageController(initialPage: index);

  final ImageProvider imageProvider;
  final Widget loadingChild;
  final Decoration backgroundDecoration;
  final dynamic minScale;
  final dynamic maxScale;
  final dynamic initialScale;
  final Alignment basePosition;
  final int index;
  final PageController pageController;

  @override
  State<StatefulWidget> createState() {
    return _FullScreenWrapperState();
  }
}

class _FullScreenWrapperState extends State<FullScreenWrapper> {
  int currentIndex;

  @override
  void initState() {
    currentIndex = widget.index;
    super.initState();
  }

  void onPageChanged(int index) {
    setState(() {
      currentIndex = index;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        constraints: BoxConstraints.expand(
          height: MediaQuery.of(context).size.height,
        ),
        child: Stack(
          alignment: Alignment.bottomRight,
          children: <Widget>[
            PhotoViewGallery(
              pageOptions: <PhotoViewGalleryPageOptions>[
                PhotoViewGalleryPageOptions(
                  imageProvider: widget.imageProvider,
                  initialScale: PhotoViewComputedScale.contained * 0.9,
                )
              ],
              loadingChild: widget.loadingChild,
              backgroundDecoration: widget.backgroundDecoration,
              pageController: widget.pageController,
              onPageChanged: onPageChanged,
            ),
          ],
        ),
      ),
    );
  }
}`
