### ISSUE TITLE
Reset method 

### ISSUE THREAD

**Issue by renancaraujo** [renancaraujo/photo_view#67]
Expose a method that will make photo view go back the initial state

**Comment by jinfagang** [comment]
@renancaraujo  It seems can be done be add a gesture detector on PhotoView... But Dont know how to go back..... any thoughts?

```dart
class HeroPhotoViewWrapper extends StatelessWidget {
  const HeroPhotoViewWrapper(
      {this.imageProvider,
      this.loadingChild,
      this.backgroundDecoration,
      this.minScale,
      this.maxScale});

  final ImageProvider imageProvider;
  final Widget loadingChild;
  final Decoration backgroundDecoration;
  final dynamic minScale;
  final dynamic maxScale;

  @override
  Widget build(BuildContext context) {
    return Container(
        constraints: BoxConstraints.expand(
          height: MediaQuery.of(context).size.height,
        ),
        child: GestureDetector(
          child: PhotoView(
          imageProvider: imageProvider,
          loadingChild: loadingChild,
          backgroundDecoration: backgroundDecoration,
          minScale: minScale,
          maxScale: maxScale,
          heroTag: "someTag",
          ),
          onTap: () {
            // pop up this
          },
        ));
  }
}
```

**Comment by renancaraujo** [comment]
@jinfagang A gesture detector to reset internal state of a widget? It does not seem to be right.

**Comment by jinfagang** [comment]
@renancaraujo Haha, waiting for your creative method, I am also stuck on this.. By the way, this hero animation on iOS not seems smooth as Android, it has a left to right animation which makes hero transition not simple enlarge animation ... I don't sure if you can understand this, but you will fill it if you have both iOS and Android device to test it.

**Comment by renancaraujo** [comment]
Micro tutorial after 0.2.0:

1. setup a custom `PhotoViewController`
2. Use its `reset` method when needed
3. The end
