### ISSUE TITLE
setState() called after dispose()

### ISSUE THREAD

**Issue by blaneyneil** [renancaraujo/photo_view#71]
setState() called after dispose(): _PhotoViewState(lifecycle state: defunct, not mounted)

it's because of the `setState` call in `_getImage()` in photo_view.dart.  likely just needs a check for `mounted`.

**Comment by renancaraujo** [comment]
Do you have any steps to reproduce this bug?
I'm having trouble to see it happening.

**Comment by blaneyneil** [comment]
it's only happened a couple of times to me - when a really quick action (like swiping to another page) would trigger a dispose() after a parent nav action.  if the `setState()` was wrapped in:

```
if (mounted) {
  setState()
}

```
   
then it would never happen.

**Comment by robsonql** [comment]
I also see this bug happen intermittently. I believe it's best practice in flutter to check before calling setState.
