### ISSUE TITLE
Could you make is so when you stop panning the image, it will slow down instead of abruptly stopping

### ISSUE THREAD

**Issue by Blakexx** [renancaraujo/photo_view#8]
I don't know if this is where feature requests go, but I will put it here. I just think this would make it work a little better.

**Comment by renancaraujo** [comment]
That can be achieved with the velocity property of `ScaleEndDetails`.

**Comment by Blakexx** [comment]
Ok thanks!

**Comment by renancaraujo** [comment]
This is passed through the only parameter in the `onScaleEnd` callback.

**Comment by renancaraujo** [comment]
Added continuity effect on drag events on #50
