### ISSUE TITLE
Add scroll physics

### ISSUE THREAD

**Issue by cbenhagen** [renancaraujo/photo_view#83]
It would be nice if the widget would feel like a `ListView`. Bonus points if it also adapts to the feel of the current OS.

Relevant flutter issues:
https://github.com/flutter/flutter/issues/23457
https://github.com/flutter/flutter/issues/20175

**Comment by cbenhagen** [comment]
I should have been more precise. This issue was about the PhotoView widget itself. When being zoomed in and moving around it would be very nice if the movement would feel like a ListView. With kinetic scrolling.

**Comment by renancaraujo** [comment]
Yes, I've been thinking about implementing ScalePhysics, PositionPhysics and least important, RotationPhysics. Of course, we will have to create another issue for that.  This one is already solved 🤣🤣
